version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g aws-cdk
      - npm install
  build:
    commands:
      - npm run build
      - cdk synth
artifacts:
  files:
    - '**/*'
